Repository tbphp/gpt-load, pull requests merged in 2025-08, with the labels that each got.

#89 feat: 统计10分钟RPM
  internal/handler/dashboard_handler.go
  internal/models/types.go
  web/src/components/BaseInfoCard.vue
  web/src/types/models.ts
Labels: enhancement

#86 feat: 分组密钥检查增加状态选项
  internal/handler/key_handler.go
  internal/services/key_manual_validation_service.go
  web/src/api/keys.ts
  web/src/components/GlobalTaskProgressBar.vue
  web/src/components/keys/KeyTable.vue
Labels: enhancement

#107 fix: 放宽验证Key的错误状态码为2XX
  internal/channel/anthropic_channel.go
  internal/channel/gemini_channel.go
  internal/channel/openai_channel.go
Labels: bug

#116 chore: release macos amd64
  .github/workflows/release-linux.yml
  .github/workflows/release-macos.yml
  .github/workflows/release-windows.yml
Labels: enhancement

#105 style: 前端优化
  web/src/components/keys/GroupFormModal.vue
Labels: bug

#118 chore: 考虑安全性，不再映射端口
  docker-compose.yml
Labels: enhancement

#146 fix(proxy): 排除404状态码避免无意义重试
  internal/proxy/server.go
Labels: enhancement

#144 style: 调整logo
  web/src/assets/logo.png
  web/src/components/Layout.vue
Labels: documentation, enhancement

#142 feat: 删除所有密钥
  internal/handler/key_handler.go
  internal/keypool/provider.go
  internal/router/router.go
  internal/services/key_service.go
  web/src/api/keys.ts
  web/src/components/keys/GroupInfoCard.vue
  web/src/components/keys/KeyTable.vue
Labels: enhancement

#141 feat: HTTP代理功能增强
  README.md
  README_EN.md
  internal/channel/factory.go
  internal/config/system_settings.go
  internal/httpclient/manager.go
  internal/models/setting_info.go
  internal/models/types.go
  internal/types/types.go
  internal/utils/config_utils.go
  web/src/api/settings.ts
  web/src/components/keys/GroupFormModal.vue
  web/src/types/models.ts
  web/src/views/Settings.vue
Labels: enhancement

#172 feat: 复制分组
  internal/handler/group_handler.go
  internal/router/router.go
  web/src/api/keys.ts
  web/src/components/keys/GroupCopyModal.vue
  web/src/components/keys/GroupInfoCard.vue
  web/src/views/Keys.vue
Labels: enhancement

#169 fix: 提升认证逻辑安全性
  internal/handler/handler.go
  internal/middleware/middleware.go
Labels: bug

#168 feat: 允许自定义Header并支持变量
  internal/channel/anthropic_channel.go
  internal/channel/channel.go
  internal/channel/gemini_channel.go
  internal/channel/openai_channel.go
  internal/handler/group_handler.go
  internal/keypool/validator.go
  internal/models/types.go
  internal/proxy/server.go
  internal/services/group_manager.go
  internal/utils/header_utils.go
  web/src/components/keys/GroupFormModal.vue
  web/src/components/keys/GroupInfoCard.vue
  web/src/components/keys/KeyTable.vue
  web/src/types/models.ts
Labels: enhancement

#108 refactor: 删除数据修复脚本
  internal/app/app.go
  internal/db/migrations/migration.go
  internal/db/migrations/v1.0.13_fix_request_logs.go
Labels: enhancement

#202 refactor: 规范错误处理
  internal/errors/uncounted_errors.go
  internal/keypool/provider.go
  internal/proxy/server.go
Labels: enhancement

#180 feat: 添加请求和响应体日志记录功能
  internal/config/system_settings.go
  internal/models/types.go
  internal/proxy/response_handlers.go
  internal/proxy/server.go
  internal/types/types.go
  web/src/api/settings.ts
  web/src/components/keys/GroupFormModal.vue
  web/src/components/logs/LogTable.vue
  web/src/types/models.ts
  web/src/views/Settings.vue
Labels: enhancement

#211 feat: 优化密钥批量操作
  internal/container/container.go
  internal/handler/handler.go
  internal/handler/key_handler.go
  internal/keypool/provider.go
  internal/router/router.go
  internal/services/key_delete_service.go
  internal/services/key_import_service.go
  internal/services/task_service.go
  web/src/api/keys.ts
  web/src/components/GlobalTaskProgressBar.vue
  web/src/components/keys/GroupInfoCard.vue
  web/src/components/keys/KeyDeleteDialog.vue
  web/src/components/keys/KeyTable.vue
  web/src/types/models.ts
Labels: bug, enhancement

#224 fix: Conflict between key search and authentication
  internal/handler/key_handler.go
  internal/services/log_service.go
  web/src/api/keys.ts
  web/src/components/keys/KeyTable.vue
Labels: bug

#218 security-hardening
  .env.example
  internal/app/app.go
  internal/config/manager.go
  internal/container/container.go
  internal/encryption/encryption.go
  internal/handler/handler.go
  internal/handler/key_handler.go
  internal/middleware/middleware.go
  internal/router/router.go
  internal/services/key_service.go
Labels: enhancement
