Repository tbphp/gpt-load, pull requests merged in 2025-07, with the labels that each got.

#19 feat: 分组名称支持更多格式
  internal/handler/group_handler.go
  web/src/components/keys/GroupFormModal.vue
Labels: enhancement

#17 Fix log apikey error
  internal/app/app.go
  internal/db/migrations/migration.go
  internal/db/migrations/v1.0.13_fix_request_logs.go
  internal/handler/log_handler.go
  internal/models/types.go
  internal/proxy/server.go
  internal/services/request_log_service.go
  internal/types/types.go
  web/src/components/logs/LogTable.vue
Labels: bug

#25 fix: 修复前端复制兼容性问题
  web/src/components/keys/GroupInfoCard.vue
  web/src/components/keys/KeyTable.vue
  web/src/utils/clipboard.ts
Labels: bug

#28 docs: 更新docker快速启动方式
  README.md
  README_EN.md
Labels: documentation

#31 feat: 密钥导出功能
  internal/container/container.go
  internal/handler/handler.go
  internal/handler/key_handler.go
  internal/handler/log_handler.go
  internal/middleware/middleware.go
  internal/router/router.go
  internal/services/key_service.go
  internal/services/log_service.go
  web/src/api/keys.ts
  web/src/api/logs.ts
  web/src/components/keys/KeyTable.vue
  web/src/components/logs/LogTable.vue
Labels: enhancement

#11 添加自动构建二进制文件功能。
  .github/workflows/build-go.yml
Labels: enhancement

#46 feat: 自定义测试路径
  internal/channel/anthropic_channel.go
  internal/channel/base_channel.go
  internal/channel/factory.go
  internal/channel/gemini_channel.go
  internal/channel/openai_channel.go
  internal/handler/group_handler.go
  internal/models/types.go
  web/src/components/keys/GroupFormModal.vue
  web/src/components/keys/GroupInfoCard.vue
  web/src/types/models.ts
Labels: enhancement

#51 typo: 秘钥 -> 密钥
  web/src/components/BaseInfoCard.vue
Labels: bug

#53 feat: 静态缓存
  internal/middleware/middleware.go
  internal/router/router.go
Labels: enhancement

#59 fix: 修复新建分组刷新数据异常
  web/src/components/keys/GroupList.vue
Labels: bug

#60 fix: Key len
  internal/models/types.go
Labels: bug

#56 feat: 认证Key分离-新增代理Key配置
  README.md
  README_EN.md
  internal/app/app.go
  internal/config/system_settings.go
  internal/handler/group_handler.go
  internal/handler/settings_handler.go
  internal/middleware/middleware.go
  internal/models/types.go
  internal/router/router.go
  internal/services/group_manager.go
  internal/types/types.go
  internal/utils/config_utils.go
  internal/utils/string_utils.go
  web/src/components/keys/GroupFormModal.vue
  web/src/types/models.ts
  web/src/views/Settings.vue
Labels: enhancement

#63 feat: 支持Gemini官方的OpenAi兼容
  internal/channel/gemini_channel.go
Labels: enhancement

#68 feat: 代理密钥优化-自动生成随机密钥和复制
  web/src/components/common/ProxyKeysInput.vue
  web/src/components/keys/GroupFormModal.vue
  web/src/components/keys/GroupInfoCard.vue
  web/src/utils/display.ts
  web/src/views/Settings.vue
Labels: enhancement
